A feature to detect if taskbar is visible or hidden
alexmercerind/windows_taskbar pull request #17
Opened 2023-08-01 15:14 UTC by nikitatg

Greetings. There is simple implementation of feature for Windows to find out if system taskbar is visible or hidden when autohide option is turned on.
Tested on Windows 10 22H2 and Flutter 3.3.10 and 3.7.12

2023-08-01 17:39 UTC, alexmercerind requested changes
nits

2023-08-01 17:39 UTC, alexmercerind commented on windows/windows_taskbar_plugin.cc
> +  static constexpr auto kIsTaskbarVisible = "isTaskbarVisible";
Please start with upper-case like other methods.

2023-08-01 17:39 UTC, alexmercerind commented on windows/windows_taskbar.cc
> +  HWND hTaskbarWnd;
Please follow [Google Style Guide for C++](https://google.github.io/styleguide/cppguide.html) (mainly naming of identifiers is concerned here, snake case for local identifiers).

Format the source files with clang-format:
https://github.com/alexmercerind/windows_taskbar/blob/b3273d58aab9d71f61b51a84d5c6fb6cf0821529/.clang-format#L1-L3

2023-08-01 17:40 UTC, alexmercerind commented
Thanks!

2023-08-02 05:50 UTC, nikitatg commented
PR was updated. Thanks for hints!

2023-08-02 05:54 UTC, merged